version: '3'

services:
  postgres:
    image: 'postgres:13'
    container_name: 'postgres-product-manager'
    ports:
    - 5432:5432
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=product-manager'